config/routes.rb
Rails.application.routes.draw do

  root 'site#index'

  # Authentication
  get '/auth/:provider/callback'   => 'sessions#create', as: :omniauth_callback
  get '/signout' => 'sessions#destroy', as: :sign_out
  get '/search' => 'site#search_gems', as: :search

  # Resources
  resources :gems, only: [:index, :show]
  resources :gems_adoptions, except: :edit
  resources :adoption_requests, only: [:index, :new, :create]
  resources :gem_ownership_transfers, only: :index
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  
  def index
    @gems_adoption_count = GemsAdoption.count
  end

  def search_gems
    page = params[:page] || 1
    @title = 'search'
    @subtitle = "for #{params[:query]}"
    @gems_adoptions = GemsAdoption.search(params[:query]).page(page)
  end
end

app/views/site/_search_gems.html.erb
<%= form_tag search_path, :method => 'get' do %>
	<div class="form-group">
    <%= text_field_tag :search, nil, placeholder: "Search gems...", class: "form-control input-lg" %>
	</div>
    <%= submit_tag "Search", :class => "btn btn-primary" %>
<% end %>

app/views/site/index.html.erb
<% page_title! 'Home' %>

<!-- Headlines -->
<br>
<h1 align="center" class="" style="color: white;"><strong>RubyGems Adoption Center</strong>
<h1 class="home__heading">Adopt and help others maintaining Gems</h1>
<div class="home__image-wrap">
  <div class="home__image"></div>
</div>

<!-- Main search form -->
<div class="home__search-wrap">
  <%= form_tag :search, id: 'man-search', method: :get do %>
    <%= search_field_tag :query, params[:query], placeholder: 'Find Gems...', autofocus: current_page?(root_url), id: 'home_query', class: 'home__search' %>
    <%= submit_tag '⌕', id: 'search_submit', name: nil, class: 'home__search__icon' %>
  <% end %>
</div>

<!-- General information -->
<div class="home__cta-wrap">
  <% if @gems_adoption_count %>
    <h2 class="home__downloads">
      <p class="gem__adoption__count"><%= number_with_delimiter(@gems_adoption_count) %></p>
      <span class="home__downloads__desc">Gems up for adoption</span>
    </h2>
  <% end %>
  <%= link_to 'Sign in with Github', '/auth/github', class: "home__join #{@gems_adoption_count.nil? ? 'no-download-count' : ''}", data: { icon: '>' } %>
</div>

app/views/site/search_gems.html.erb
<% page_title! 'Search' %>

<header class="gems__header">
  <p class="gems__meter">
    <%= page_entries_info @gems_adoptions, entry_name: 'Gem' %>
  </p>
</header>

<% if @gems_adoptions.any? %>
  <%= render @gems_adoptions %>
  <%= paginate @gems_adoptions %>
<% end %>