config/routes.rb
Rails.application.routes.draw do

  root 'site#index'

  # Authentication
  get '/auth/:provider/callback'   => 'sessions#create', as: :omniauth_callback
  get '/signout' => 'sessions#destroy', as: :sign_out
  get '/search' => 'site#search_gems', as: :search

  # Resources
  resources :gems, only: [:index, :show]
  resources :gems_adoptions, except: :edit
  resources :adoption_requests, only: [:index, :new, :create]
  resources :gem_ownership_transfers, only: :index
end

app/models/adoption_request.rb
class AdoptionRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :gems_adoption
  validates :gems_adoption, :user, presence: true

  default_scope { order('created_at DESC') }
end

app/controllers/adoption_requests_controller.rb
class AdoptionRequestsController < ApplicationController
  before_action :require_login

  def index
    @gems_adoptions = current_user.gems_adoptions.includes(:ruby_gem, adoption_requests: :user)
  end

  def new
    @gem_adoption = GemsAdoption.find(params[:id])
    @adoption_request = @gem_adoption.adoption_requests.build
  end

  def create
    @adoption_request = current_user.adoption_requests.build(adoption_request_params)
    if @adoption_request.save
      NotificationMailer.email_new_adoption_request(current_user, @adoption_request.gems_adoption.ruby_gem).deliver_now
      flash[:success] = 'Adoption request sent'
      redirect_to gem_path(@adoption_request.gems_adoption.ruby_gem)
    else
      render :new
    end
  end

  private

  def adoption_request_params
    params.require(:adoption_request).permit(:gems_adoption_id, :description)
  end
end

app/views/adoption_requests/_adoption_request.html.erb
<div>
  <!-- Adoption request information -->
  <p><b><%= link_to adoption_request.user.username, adoption_request.user.rubygems_profile, target: 'blank' %></b> applied to adopt this gem on <b><%= l(adoption_request.created_at, format: "%B %d, %Y.").capitalize %></b></p>
  <% if adoption_request.description? %>
    <blockquote >
      <p><%= adoption_request.description %></p>
    </blockquote>
  <% end %>

  <!-- Actions -->
  <ul class="list-inline">
    <li><%= link_to 'Accept request', gems_adoption_path(id: adoption_request.id), method: :put, :class => "btn btn-primary btn-sm", data: { confirm: 'Are you sure?' } %></li>
    <li>or</li>
    <li><%= mail_to adoption_request.user.email, "Reply via e-mail", data: { toggle: "tooltip", placement: "right", title: adoption_request.user.email } %></li>
  </ul>
</div>
<hr>

app/views/adoption_requests/index.html.erb
<% page_title! 'Adoptions Requests' %>

<h1>Adoption Requests</h1>
<% if @gems_adoptions.empty? %>
  <p>You don't have gems up for adoption</p>
<% else %>
  <% @gems_adoptions.each do |gem_adoption| %>
    <div>
      <h2 class="text-muted gem-name"><%= gem_adoption.ruby_gem.name %></h2><br>
      <%= render(gem_adoption.adoption_requests) || "<p>No adoption requests yet.</p>".html_safe %>
    </div>
  <% end %>
<% end %>

app/views/adoption_requests/new.html.erb
<% page_title! 'Adoption Request Form' %>

<%= form_for @adoption_request do |f| %>
  <h1><%= @gem_adoption.ruby_gem.name %></h1>
  <% if @adoption_request.errors.any? %>
    <div>
      <p><%= pluralize(@adoption_request.errors.count, "error") %> Prohibited this adoption request from being saved:</p>
      <ul>
        <% @adoption_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br>
  <%= f.hidden_field :gems_adoption_id %>
  <p><%= f.text_area :description, placeholder: 'Why do you want to adopt this gem?', class: 'form-control', rows: 5 %></p>
  <ul class="list-inline">
    <li><%= f.submit "Send adoption request", class: 'btn btn-primary' %></li>
    <li><%= link_to 'Cancel', gem_path(@gem_adoption.ruby_gem), class: 'btn btn-danger' %></li>
  </ul>
<% end %>

app/views/adoption_requests/show.html.erb
<h1>Adoption Request for <%= @adoption_request.gems_adoption.ruby_gem %></h1>
<p><strong>Description: </strong><%= @adoption_request.description %></p>
<button>Accept</button>