config/routes.rb
Rails.application.routes.draw do

  root 'site#index'

  # Authentication
  get '/auth/:provider/callback'   => 'sessions#create', as: :omniauth_callback
  get '/signout' => 'sessions#destroy', as: :sign_out
  get '/search' => 'site#search_gems', as: :search

  # Resources
  resources :gems, only: [:index, :show]
  resources :gems_adoptions, except: :edit
  resources :adoption_requests, only: [:index, :new, :create]
  resources :gem_ownership_transfers, only: :index
end

app/controllers/gems_controller.rb
class GemsController < ApplicationController
  before_action :require_login, only: [:index]

  def index
    @ruby_gems = current_user.ruby_gems.order(:name)
  end

  def show
    @ruby_gem = RubyGem.find(params[:id])
    @gems_adoption = @ruby_gem.gems_adoption
    @adoption_owner = @gems_adoption.user
    @title = @ruby_gem.name
    if @gems_adoption && logged_in?
      @adoption_request =  current_user.adoption_requests.find_by_gems_adoption_id(@gems_adoption.id)
    end
  end
end

app/views/gems/index.html.erb
<% page_title! 'My Gems' %>

<h1><%= current_user.username %></h1>
<h3 class="text-muted"><%= pluralize(@ruby_gems.count, 'Gem') %></h3>
<hr>

<% if @ruby_gems.empty? %>
  <h3 class="text-muted">You haven't pushed any gems yet.</h3>
<% else %>
  <% @ruby_gems.each do |ruby_gem| %>
    <div class="clearfix">
      <h4 class="pull-left"><%= link_to ruby_gem.name, gem_path(ruby_gem) %></h4>
      <% if ruby_gem.gems_adoption %>
        <%= link_to 'Remove from adoption', ruby_gem.gems_adoption, method: :delete, class: 'btn btn-danger pull-right', data: { confirm: 'Are you sure?' } %>
      <% else %>
        <%= link_to 'Put up for adoption', new_gems_adoption_path(id: ruby_gem.id), class: 'btn btn-primary pull-right' %>
      <% end %>
    </div>
    <hr>
  <% end %>
<% end %>

app/views/gems/show.html.erb
<% page_title! "Gem #{@ruby_gem.name}" %>

<div class="l-overflow">
  <!-- Gem Information / Left container -->
  <div class="l-colspan--l colspan--l--has-border">
    <div class="gem__intro">
      <div id="markup" class="gem__desc">
        <span> <%= @ruby_gem.info %></span>
        <%= link_to "Read more", @ruby_gem.project_uri, target: 'blank' %>.
      </div>
    </div>

    <div class="">
      <h3 class="t-list__heading">About the adoption:</h3><br>
      <div class="gem__desc">
        <% if @gems_adoption.description.present? %>
          <p><%= @gems_adoption.description %></p><br>
        <% end %>
        <p>
          <b><%= link_to @adoption_owner.username, @adoption_owner.rubygems_profile, target: 'blank' %></b> put this gem up for adoption on <b><%= l(@gems_adoption.created_at, format: "%B %d, %Y.").capitalize %></b>
        </p>
      </div>
    </div>
  </div>

  <!-- Actions / Right container -->
  <div class="gem__aside l-col--r--pad">
    <div class="gem__downloads-wrap">
      <% if logged_in? %>
        <% if current_user.owns_gem?(@ruby_gem) %>
          <% if @gems_adoption %>
              <%= link_to 'Remove from adoption', @gems_adoption, method: :delete, data: { confirm: 'Are you sure?' } %>
              <%= link_to 'View adoption requests', :adoption_requests %>
          <% else %>
            <%= link_to 'Put up for adoption', new_gems_adoption_path(id: @ruby_gem.id) %>
          <% end %>
        <% else %>
          <% if @adoption_request %>
            <!-- TODO: Button to cancel adoption request -->
            <p>You are waiting for a response to your adoption request</p>
          <% else %>
            <%= link_to 'Adopt this gem', new_adoption_request_path(id: @gems_adoption.id) %>
          <% end %>
        <% end %>
      <% else %>
        <%= link_to 'Adopt this gem', new_adoption_request_path(id: @gems_adoption.id) %>
      <% end %>
    </div>
  </div>
</div>